#Server
server:
  SERVER_URL: "0.0.0.0:8080"

# Database
database:
  DATABASE_URL: "postgres://postgres:admin@db:5432/postgres"

referenceValues:
  DIFF_VALUE: 35
  TOKENS_VALUE: 55
  METRICS_VALUE: 55

apiKey: "AIzaSyAcjDVb4RZbSuvUs3B4TguEmZI0r-hQPvI"

